application:
  resources:
    fxml:
      relative-path: '/fxml/{fileName}.fxml'
    icons:
      relative-path: '/icons/{fileName}.png'

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}
    redirect-uri: ${SPOTIFY_REDIRECT_URI}
    scope: 'playlist-read-collaborative,playlist-modify-private,playlist-modify-public,
            playlist-read-private,user-modify-playback-state,user-read-currently-playing,
            user-read-playback-state,user-read-private,user-read-email,user-library-modify,
            user-library-read,user-follow-modify,user-follow-read,user-read-recently-played,
            user-top-read,app-remote-control'

musixmatch:
  api:
    key: ${MUSIXMATCH_API_KEY}
  client:
    settings:
      default-page-size: 1

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
  client:
    settings:
      default-page-size: 1
      embedded-url: "https://www.youtube.com/embed/"

jx-browser:
  auth:
    license-key: ${JX_BROWSER_LICENSE_KEY}
